depromeet/InsightOut-Server

.github/workflows/deploy.yml

deploy.yml 환경 변수 수정

---

.github/workflows/deploy.yml

dev 브랜치에 푸시될 때만 deploy.yml 실행되게 변경

---

package.json
src/apps/server/auth/auth.module.ts
src/apps/server/auth/auth.service.ts
src/modules/api/api.module.ts
src/modules/api/api.service.ts
yarn.lock

#32 
계속 fetch is not defined로 떠서 XML 요청을 axios로 사용합니다.

[Feature] fetch 함수를 axios 요청으로 변경

---

src/apps/server/auth/auth.service.ts
src/apps/server/guards/strategies/jwt.strategy.ts
src/modules/database/schema.prisma

위 구조를 고려하여 엔티티를 작성했습니다.
resume의 pk를 question이라는 문항 테이블의 pfk로 씁니다.

[Feature] 자기소개서 entity 작성

---

appspec.yml
deploy-before.sh
deploy-run.sh

feat: infra appspec.yml file 추가

---

src/libs/modules/database/schema.prisma

---
https://www.notion.so/depromeet/05-27-x-or-7438bc04b7034ce8aced336a5d92d9d9
해당 논의에서 바뀌 내용을 정리하고, 추가적으로 누락된 속성들을 정리해야 합니다.
---
DB 타입을 조금 더 정확하게 정의하고, 역량 키워드 테이블과 피드백 테이블을 추가합니다.
---
#65 
---
추가적으로 컬럼 속성 수정할 부분이 있으면 말씀해 주세요.
---

[Feature] 컬럼 속성 수정

---

src/apps/server/auth/auth.service.ts
src/libs/modules/database/schema.prisma

Resolves: #9
---
uid 가 not null인데 query에 안 넣어줘서 오류가 발생했습니다.
---
prisma query에 uid를 추가했습니다.
---
---
---

[HOTFIX] uid 필수값 누락 수정

---

src/apps/server/main.ts

Resolves: #94
---
swagger에서 8080포트로 요청을 보내서 요청이 닿지를 않습니다.
---
Swagger 셋업에서 포트를 삭제했습니다.
---
#94 
---
---

[Fix] 개발 서버 origin에서 port 삭제하여 80포트로 요청이 들어오도록 수정

---

src/apps/server/app.module.ts
src/apps/server/test/dtos/post-issue-test-token.dto.ts
src/apps/server/test/test.controller.ts
src/apps/server/test/test.service.ts
src/apps/server/users/dtos/post-feedback.dto.ts
src/apps/server/users/user.controller.ts
src/apps/server/users/user.module.ts
src/apps/server/users/user.service.ts
src/libs/modules/database/repositories/feedback.repository.ts

Resolves: #96
---
스웨거에서 @ApiProerty를 명세해주지 않아서 테스트 토큰 발급 부분에서 body를 받을 수가 없습니다.
Feedback API가 필요해서 구현했습니다.
---
테스트 토큰에서 @ApiProperty를 추가하여 스웨거에서 보일 수 있도록 했습니다.
피드백 테이블에 row를 생성합니다.
---
#96, #98
---
---

[Fix, Docs] test token 발급 API 명세 추가 및 피드백 API 생성

---

src/apps/server/app.controller.ts
src/apps/server/experiences/dto/res/createExperienceInfo.res.dto.ts
src/apps/server/resumes/controllers/question.controller.ts
src/apps/server/resumes/controllers/resumes.controller.ts
src/apps/server/resumes/dtos/get-question.dto.ts
src/apps/server/resumes/dtos/post-question.dto.ts
src/apps/server/resumes/services/question.service.ts
src/apps/server/resumes/services/resumes.service.ts
src/apps/server/test/test.controller.ts
src/apps/server/users/user.controller.ts
src/libs/modules/database/schema.prisma

---
자기소개서 문항 조회하는 기능이 필요합니다.
---
get method에 resource를 하나 가져오므로 path parameter로 자기소개서 문항 한 개를 가져옵니다.
---
#102 
---
---
프론트분들께 의견 여쭤봤었는데 id 속성이 더 편하다고 하시네요!

[Feature] 자기소개서 문항 조회 API 추가

---

src/apps/server/app.module.ts
src/apps/server/auth/auth.controller.ts
src/apps/server/auth/auth.module.ts
src/apps/server/auth/auth.service.ts
src/apps/server/auth/dtos/post-signin.dto.ts
src/apps/server/auth/types/user.type.ts
src/apps/server/onboarding/docs/get-onboarding.doc.ts
src/apps/server/onboarding/dtos/get-onboarding.dto.ts
src/apps/server/onboarding/onboarding.controller.ts
src/apps/server/onboarding/onboarding.module.ts
src/apps/server/onboarding/onboarding.service.ts
src/apps/server/resumes/dtos/post-resume.dto.ts
src/apps/server/resumes/services/resumes.service.ts
src/libs/modules/database/repositories/onboarding.repository.ts
src/libs/modules/database/schema.prisma

---
온보딩 기능을 위해 위와 같은 flow로 온보딩, 툴팁을 노출시킵니다.
---
```ts
// ****************************
// *********** 온보딩 ***********
// ****************************
// 회원가입 시 모든 온보딩 처리를 생성합니다.
model Onboarding {
userId Int @id
experience Boolean @default(false) // 경험분해 온보딩 여부
experienceStepper Boolean @default(false) @map("experience_stepper") // 경험분해 stepper 온보딩 여부
resume Boolean @default(false) // 자기소개서 작성 온보딩 여부
collection Boolean @default(false) // 모아보기 온보딩 여부
User User @relation(references: [id], fields: [userId])
}
```
```ts
async signin(
@Body() _: PostSigninRequestBodyDto,
@User() user: UserPayload,
@Res({ passthrough: true }) response: Response,
): Promise<ResponseEntity<PostSigninResponseDto & { onboarding: GetAllOnboardingsResponseDto }>> {
const userId = await this.authService.signin(user); …
```

[Feature] 온보딩 여부 조회 API 추가

---

src/apps/server/resumes/controllers/resumes.controller.ts
src/apps/server/resumes/dtos/get-resume.dto.ts
src/apps/server/resumes/services/resumes.service.ts

---
get /resume api의 응답값 예시가 swagger에서 잘 보이지 않아 추가가 필요합니다.
---
기존 타입을 수정했습니다.
---
---
---

[Hotfix/Docs]: get resumes response type 수정

---

src/apps/server/resumes/controllers/resumes.controller.ts
src/apps/server/resumes/docs/get-resume.doc.ts
src/apps/server/resumes/dtos/get-resume.dto.ts
src/apps/server/resumes/services/resumes.service.ts

---
모아보기에서 자기소개서를 모아보기 위해, 자기소개서 제목들을 클릭해 원하는 자기소개서의 문항들을 찾아낼 수 있습니다.
---
```ts
/**
* 자기소개서 제목만 조회합니다.
*
* 모아보기에서 제목을 통해 자기소개서 문항들을 조회하기 위해 사용됩니다.
* @param userId 유저 id입니다.
* @returns 유저가 작성한 자기소개서의 제목들을 모두 반환합니다.
*/
async getAllResumesTitle(userId: number): Promise<GetOneResumeWithTitleResponseDto[]> {
const resumeTitleWithResumeId = await this.resumesRepository.findMany({
where: { userId },
select: { id: true, title: true, createdAt: true, updatedAt: true },
orderBy: { createdAt: 'desc' },
});
const getAllResumesTitleResponseDto = resumeTitleWithResumeId.map((resume) => new GetOneResumeWithTitleResponseDto(resume));
return getAllResumesTitleResponseDto;
}
```
---
#119 
---
---
단순 CRUD API라서 금방 했습니다.

[Feature] 자기소개서 제목 조회 API

---

src/libs/modules/database/schema.prisma

[Hotfix] 자기소개서 제목 길이를 13에서 20으로 수정

---

src/apps/server/main.ts
src/libs/modules/env/env.enum.ts

---
cors error가 뜨는 것 같아서 프론트 주소를 origin에 등록합니다.
---
---
#155 
---
---

[Feature] frontend origin을 cors origin에 등록

---

src/apps/server/resumes/services/resume.service.spec.ts

---
resume title 가져오는 api의 성공 케이스를 테스트하지 않아서 추가합니다.
---
---
---
---

[Test] resume title 가져오는 api 응답 테스트

---

src/apps/server/resumes/services/resume.service.spec.ts

---
자기소개서 한 개 조회하는 API의 handler를 테스트합니다.
---
- 자기소개서 한 개 조회 성공
- 자기소개서 한 개 조회 실패
---
#175 
---
---

[Test] 자기소개서 한 개 조회 API Handler 테스트

---

src/apps/server/auth/auth.controller.ts
src/apps/server/auth/auth.service.ts

---
쿠키 내릴 때 옵션을 변경해서 프론트에서 사용할 수 있게 하고자 합니다.
---
---
---
---

[Feature] cookie option에 sameSite none, secure true 추가

---

src/apps/server/main.ts

---
global prefix를 설정
---
---
---
---

[Chore] global prefix를 api로 설정

---

buildAndStart.sh

---
쿠키 옵션을 다르게 가져가야 해서 prod인지 체크가 중요하므로 서버 실행 스크립트를 수정합니다.
---
---
---
---

[Chore] 서버 실행 스크립트 수정

---

src/apps/server/main.ts

---
프론트에서 로컬로 테스트할 수 있도록 cors를 풀었습니다.
---
---
---
---

[Hotfix] allow-origin 에 모든 오리진 추가

---

src/apps/server/ai/ai.controller.ts
src/apps/server/ai/ai.module.ts
src/apps/server/ai/ai.service.ts
src/apps/server/ai/dto/res/createAiKeywordsAndResume.res.dto.ts
src/apps/server/ai/providers/ai.provider.ts
src/apps/server/auth/auth.service.ts
src/apps/server/experiences/dto/res/getExperience.res.dto.ts
src/apps/server/experiences/experience.module.ts
src/apps/server/experiences/services/experience-capability.service.ts
src/apps/server/experiences/types/count-experience-and-capability.type.ts
src/libs/modules/database/repositories/ai-capability.repository.ts
src/libs/modules/database/repositories/experience.repository.ts
src/libs/modules/database/schema.prisma

- aiCapability를 capability로 통합 => capability keywordType으로 역량을 구분할 수 있도록 수정하였습니다.
---
---
#181 
---
---
- 스키마가 변경되면서 로직에 사이드 이펙 생기는 부분 수정하였습니다 :)
---

[#181] 데이터베이스 스키마 수정

---

src/apps/server/experiences/controllers/experience.controller.ts
src/apps/server/experiences/dto/req/get-experience.dto.ts
src/apps/server/main.ts
src/libs/pagination/pagination-meta.dto.ts
src/libs/pagination/pagination-option.dto.ts
src/libs/pagination/pagination.dto.ts
src/libs/pagination/pagination.type.ts

---
페이지네이션이 향후에 꼭 필요할 기능이라서 미리 추가했습니다.
---
```ts
export class PaginationOptionsDto {
@ApiPropertyOptional({
description: criteriaDiscription,
example: 'createdAt',
default: 'createdAt',
type: String,
})
@IsString()
@IsNotEmpty()
@IsOptional()
readonly criteria?: string | undefined;
@ApiPropertyOptional({ description: orderDiscription, enum: OrderBy, default: OrderBy.asc })
@IsEnum(OrderBy)
@IsOptional()
readonly order?: OrderBy = OrderBy.asc;
@ApiPropertyOptional({
description: '### 가져올 페이지',
minimum: 1,
default: 1,
type: Number,
})
@Type(() => Number)
@IsInt()
@Min(1)
@IsOptional()
readonly page?: number = 1;
@ApiPropertyOptional({
description: '### 페이지 당 가져올 데이터 개수',
minimum: 1,
maximum: 50,
default: 3,
type: Number,
})
@Type(() => Number)
@IsInt()
@Min(1)
@Max(50)
@IsOptional() …
```

[Feature] 페이지네이션 세팅

---

src/apps/server/experiences/controllers/experience.controller.ts
src/apps/server/experiences/dto/req/upsertExperience.dto.ts
src/apps/server/experiences/dto/res/createExperience.res.dto.ts
src/apps/server/experiences/dto/res/updateExperienceInfo.res.dto.ts
src/apps/server/experiences/dto/res/upsertExperienceInfo.res.dto.ts
src/apps/server/experiences/markdown/experience.md.ts
src/apps/server/experiences/services/experience.service.ts
src/libs/modules/database/repositories/experience.repository.ts

- 경험 분해 upsert를 update만 할 수 있도록 변경
---
- 경험 분해 탭을 클릭하면 최초로 빈 경험 분해 생성 -> 이후는 모두 업데이트 처리되면서 upsert를 update로 수정하였습니다.
---
#211 
---
---
- 화이팅! 이성태!
---

Feature/#211/pid 211/upsert to update

---

buildAndStart.sh

---
서버 실행 스크립트를 yarn prod로 수정합니다!
---
---
#222
---
---

[Feature] 서버 실행 shell 스크립트 수정

---

src/apps/server/auth/auth.service.ts
src/apps/server/common/filters/custom-exception.filter.ts
src/libs/modules/database/schema.prisma

---
---
- onDelete가 없어서 fk constraint 관련 문제를 감지하는 것을 수정했습니다.
- 에러 발생 시 유저 삭제된 것을 롤백합니다.
- 회원 탈퇴는  중요한 사항이라서 serializable로 트랜잭션 격리 수준을 설정했습니다.
---
#228
---
---

[Fix] 회원탈퇴 시 데이터베이스에서 유저가 삭제되지 않는 에러 수정                                                  

---

src/libs/modules/database/schema.prisma

---
aiResume가 자꾸 700자를 넘어가서 수정합니다.
---
---
---
---

[Chore] aiResume 의 content 길이를 1000으로 수정

---

src/apps/server/ai/ai.service.ts

---
timeout 때문에 계속 처리가 안되는 버그를 수정합니다.
throw error 를 하지 않아서 정상 처리되는 버그를 수정합니다.
---
---
---
---

[Fix]: ai resume 작성 부분 transaction timeout 연장

---

src/apps/server/experiences/controllers/experience.controller.ts

---
GET /api/:experienceId API 때문에 다른 API가 동작하지 않는 버그를 수정합니다.
---
---
---
---

[Fix] get experienceId 순서를 가장 뒤로 이동

---

src/apps/server/experiences/services/experience-capability.service.ts
src/apps/server/experiences/services/experience.service.ts

- 역량 키워드가 없을 경우 빈 배열 내려 주도록 변경
---
---
---
---
---

키워드 없을 시 에러 아닌 빈 배열 내려주기

---

.vscode/launch.json
src/apps/server/common/consts/experience-attribute.const.ts
src/apps/server/experiences/controllers/experience.controller.ts
src/apps/server/experiences/dto/res/getExperience.res.dto.ts
src/apps/server/experiences/interface/experience-select.interface.ts
src/apps/server/experiences/markdown/experience.md.ts
src/apps/server/experiences/services/experience.service.ts
src/libs/dtos/success-common-response.dto.ts
src/libs/modules/database/repositories/experience.repository.ts
src/libs/pagination/pagination-meta.dto.ts
src/libs/pagination/pagination-option.dto.ts

---
모아보기에서 AI 추천 키워드와 요약 키워드가 추가적으로 필요해서 응답에 포함했습니다.
---
조금 헷갈려서 더 간단하게 메서드를 수정했습니다. 동현님께서 작성하신 코드 삭제하고 새로 만들었습니다. 처음부터 새로 구현하는 게 더 쉬울 것 같아서 ㅎㅎ..
```ts
/**
* # 경험 카드 모두 조회
*
* ## 1. 설명
*
* 유저가 작성한 경험 카드를 모두 조회합니다. 페이지네이션, 일부 조회, capabilityId를 통한 필터링이 가능합니다.
*
* ## 2. 사용 방법
*
* - select는 쿼리에서 조회할 값들을 의미합니다. 이를 제외하고 기본적으로 반환해야 하는 값들은 id, title, startDate, endDate, experienceStatus, summaryKeywords, ExperienceCapability, AiResume 입니다.
* ...select 스프레드 연산자로, 조회할 컬럼을 입력해 주세요.
* - pagination은 페이지네이션에 필요한 인자들입니다.
*   - criteria는 정렬 기준을 의미합니다. 기본값은 id입니다.
*   - order는 정렬 순서를 의미합니다. 기본값은 'desc', 내림차순입니다.
*   - take는 한 페이지에 보여줄 데이터의 개수를 의미합니다. 기본값은 3입니다.
*   - skip은 건너뛸 row의 개수입니다. (page - 1) * take로 구합니다.
*
* ## 3. 응답값
*
* @param userId 유저 고유 아이디
* @param select 추가적으로 조회할 컬럼들
* @param pagination …
```

[Feature] 모아보기 조회 시 키워드를 모두 반환하도록 수정

---

src/apps/server/ai/ai.controller.ts
src/apps/server/auth/auth.controller.ts
src/apps/server/experiences/controllers/experience.controller.ts
src/apps/server/experiences/services/experience.service.ts
src/apps/server/resumes/controllers/question.controller.ts
src/apps/server/resumes/controllers/resumes.controller.ts

- API Controller 순서를 수정했습니다.
---
---
#257 
---
---
- get -> post -> put(patch) -> delete 순으로 변경했습니다.
- experience의 get의 경우 experienceId가 있는 Get은 하위로 내렸습니다!
---

feat: get -post -put-delete 순으로 controller 정리

---

src/apps/server/ai/ai.controller.ts
src/apps/server/ai/ai.service.ts
src/apps/server/experiences/controllers/experience.controller.ts
src/apps/server/experiences/services/experience.service.ts
src/libs/modules/database/repositories/experience.repository.ts

---
ai 서비스에서 userId와 함께 조회하지 않는 부분이 있어서 userId를 추가로 유효성 검사할 수 있도록 수정합니다.
---
---
#260 #261 #262 #263
---
---
@PracticeEveryday 동현님 야근하시니까 제가 했습니다!

[Fix] ai 서비스 사용 시 userId를 받도록 수정

---

src/apps/server/common/consts/time.const.ts
src/apps/server/common/decorators/timeout.decorator.ts
src/apps/server/common/interceptors/timeout.interceptor.ts
src/apps/server/test/dtos/timeout-test.dto.ts
src/apps/server/test/test.controller.ts

---
timeout인지 아니면 openai API 문제인지 확인해보고자 timeout을 의도적으로 만들 수 있는 API 두 개를 만들었습니다.
- GET /api/test/timeout: 별도의 타임아웃 에러 없이 원하는 시간 만큼 딜레이를 설정하여 timeout을 테스트할 수 있습니다.
- GET /api/test/timeout/check: AI 자기소개서가 대강 30초가 지나면 500에러가 발생하므로 40초 정도의 제한시간을 두고 API 응답이 길어져 timeout 예외를 일으키면 어떻게 되는지 테스트할 수 있습니다.
어차피 비동기로 작업하니까 다른 API에 직접적인 영향은 없습니다.
---
```ts
import { Injectable, NestInterceptor, ExecutionContext, CallHandler, RequestTimeoutException } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { Observable, throwError, TimeoutError } from 'rxjs';
import { catchError, timeout } from 'rxjs/operators';
/**
* ## 타임아웃 인터셉터
*
* 원하는 타임아웃에서 벗어나면 408 타임아웃 에러를 반환합니다. 프론트 & 백 타임아웃 확인용입니다.
*/
@Injectable()
export class TimeoutInterceptor implements NestInterceptor {
constructor(private …
```

[Feature] timeout 확인용 API 추가

---

src/apps/server/common/consts/experience-attribute.const.ts
src/apps/server/experiences/dto/req/updateExperience.dto.ts
src/apps/server/experiences/dto/res/createExperience.res.dto.ts
src/apps/server/experiences/dto/res/getExperienceById.res.dto.ts
src/apps/server/experiences/dto/res/updateExperienceInfo.res.dto.ts
src/apps/server/experiences/interface/experience-select.interface.ts
src/apps/server/experiences/services/experience.service.ts
src/libs/modules/database/repositories/experience.repository.ts
src/libs/modules/database/schema.prisma

- utilization(역량 활용)필드를 더 이상 사용하지 않아서 삭제 하였습니다.
---
---
#259
---
---
- 성태님 감사합니다!!
---

feat: utilization 삭제 << 더이상 사용하지 않음

---

src/apps/server/ai/ai.service.ts
src/apps/server/ai/prompt/keywordPrompt.ts
src/libs/modules/open-ai/interface/aiResponse.interface.ts
src/libs/modules/open-ai/open-ai.service.ts

[Feature] AI 자기소개서 추천 문항 프롬프트 개선

---

src/apps/server/ai/ai.service.ts

- 경험 카드 생성 프롬프트 시 Status를 DONE으로 업데이트 하도록 구현했습니다 :)
---
---
#277 
---
---
---

[#277] 프롬프트 시 Status Done으로 변경해주기

---

src/apps/server/auth/auth.service.ts

---
유저의 socialId, uid로 중복 검사를 하고 있었는데 저 두 개 값이 지맘대로 변하네요 그래서 이메일 검사로 바꿨습니다.
---
---
#292 
---
---
급히 핫픽스로 반영해야 해서 선머지 하겠습니다!

[Hotfix] 유저 중복 검사를 email로 수행

---

src/libs/modules/database/schema.prisma

---
---
---
---
---
이것도 급해서 바로 선머지 할게요!! 자기소개서 문항 추천이 있으면 회원 탈퇴가 안 돼요! 그래서 onDelete를 Cascade로 바꿨습니다.

[Hotfix] experience와 ai-capability의 onDelete를 cascade로 변경

---

src/libs/modules/database/schema.prisma

---
---
---
---
---
얘도 바로 선머지 하겠습니다... 죄송해요 자꾸 바로 머지해서

[Hotfix] experiece_capability와 capability의 onDelete를 Cascade로 변경

---

.github/workflows/deploy-main.yml
src/apps/server/main.ts

- prod server 스웨거 반영 및 main서버 github action 환경 변수 업데이트
---
---
#287  #283 
---
---
- 가보자고
---

[#287] swagger main서버 업데이트, githubAction 수정

---

src/apps/server/experiences/controllers/experience.controller.ts
src/apps/server/experiences/dto/res/delete-experience.res.dto.ts
src/apps/server/experiences/markdown/experience.md.ts
src/apps/server/experiences/services/experience.service.ts
src/libs/modules/database/repositories/experience.repository.ts

- 경험 분핵 삭제 API를 구현했습니다.
---
```
{
"statusCode": 201,
"success": true,
"data": {
"isDeleted": true
}
}
```
---
#303
---
---
- 성공시 isDeleted에 true를 실패시 false를 반환합니다 👍 
---

[#303] experience 삭제 API

---

src/apps/server/ai/ai.service.ts
src/libs/modules/open-ai/open-ai.service.ts
src/libs/utils/respone.entity.ts

---
AI 추천 자기소개서가 700자로 제한해도 1000자로 뱉어냅니다.
임시방편으로 1000자에서 잘라냅니다.
any 타입에 객체 프로퍼티 접근은 해당 데이터가 undefined인 경우 에러가 발생하여 옵셔널 프로퍼티로 일단 에러 막아뒀습니다.
---
---
#305
---
---

[Feature] AI 응답을 substring으로 잘라서 저장

---

src/libs/modules/database/repositories/experience.repository.ts

---
자기소개서 작성하는 페이지의 오른쪽 aside에 경험카드 모아보기 탭이 있는데, 이게 저희 API 특성 상 DONE이지만 내용물이 비어 있는 경우가 있어서, 이것까지 다 확인해서 유효한 경험카드만 전달할 수 있도록 했습니다.
---
```ts
experiences = experiences.filter((experience) => {
if (experience.experienceStatus === ExperienceStatus.DONE) {
return (
experience.title &&
experience.situation &&
experience.task &&
experience.action &&
experience.result &&
experience.startDate instanceof Date &&
experience.endDate instanceof Date &&
experience.ExperienceInfo.analysis &&
experience.AiResume &&
experience.ExperienceCapabilities.length &&
experience.AiRecommendQuestions.length &&
experience.summaryKeywords.length
);
}
return true;
});
return experiences;
```
무지성 하드코딩 해버렸습니다... 살짝 좀 아쉽긴 한데 제일 심플해서 ㅎ..
---
#309 
---
더 좋은 검사 로직이 있으면  추천해 주시죠!
---

[Feature] 유효한 경험 카드인지 검사하는 로직 추가

---

src/libs/modules/database/repositories/experience.repository.ts

- 경험 조회사 analysis가 조회되지 않는 버그 수정
---
```
"ExperienceInfo": {
"experienceId": 3,
"experienceRole": "UI/UX 디자이너",
"motivation": "개발자와 협업 역량을 기르기 위해 하게 됨",
"analysis": "개발 기간이 짧아서 빠른 기간 내에 런칭을 완료해야 했는데 4개월 만에 출시에 성공하게 된 것은 정말 대단한 업적입니다! 효율적인 업무 분담과 철저한 일정 관리로 팀원들과의 원활한 협업능력을 발휘하셨네요. 이번 프로젝트에서의 성과는 그야말로 훌륭한 일입니다. 👏🎉"
},
```
---
#316 
---
---
---

fix: experienceInfo에서 analysis 내려오지 않는 부분 수정

---

src/apps/server/experiences/dto/res/getExperienceCardInfo.res.dto.ts
src/apps/server/experiences/services/experience.service.ts
src/apps/server/experiences/types/experience-card.type.ts
src/libs/modules/database/repositories/experience.repository.ts

- experienceStatus 내려 주지 않는 부분 수정
---
---
---
---
---

fix: ExperienceStatus 안내려주는 부분 추가

---

src/apps/server/experiences/dto/res/getExperience.res.dto.ts

- startDate, endDate가 null일 때 null로 내려갈 수 있도록 수정했습니다.
---
---
---
---
---

bug: startDate, endDate null일 때 null로 내리기

---

src/apps/server/experiences/dto/req/get-count-of-experience-and-capability.req.dto.ts
src/apps/server/experiences/services/experience.service.ts
src/apps/server/experiences/types/count-experience-and-capability.type.ts
src/libs/modules/database/repositories/capability.repository.ts
src/libs/modules/database/repositories/experience.repository.ts

---
키워드가 조회는 되는데 경험 카드가 없는 문제를 해결했습니다.
동현님께서 말씀해주신 대로, AI 까지 고려하면 꽤 복잡해서 AI는 고려 안 하고 유저만 고려했습니다.
---
---
#313 
---
---

[Feature] check experience capability

---

src/apps/server/ai/dto/res/getAiResume.res.dto.ts
src/libs/modules/database/repositories/ai-resume.repository.ts

- experienceId가 필요하여 같이 내려줄 수 있도록 수정했습니다 :)
---
```
"AiResumes": [
{
"id": 1,
"experienceId": 1,
....
"updatedAt": "2023-06-18T13:14:03.698Z",
"AiCapabilities": [
"협업 능력",
"추진력"
]
}
]
}
```
---
---
---
---

[#327] bug: experienceId 같이 내려주기

---

src/apps/server/experiences/dto/res/get-count-of-experience-and-capability.res.dto.ts
src/apps/server/experiences/services/experience.service.ts

---
키워드 개수가 필터링이 잘못 되어 있어서 조금 튑니다. 그래서 수정해줬습니다.
---
---
#314 
---
---

[Fix] 키워드 개수가 안 맞는 에러 수정

---

README.md

---
리드미 내용을 보충합니다.
---
리드미 내용을 추가했습니다.
https://github.com/depromeet/InsightOut-Server/blob/docs/%23334/readme/README.md
위 주소에서 확인해 주세요!
---
#334 
---
---

[Docs] 리드미 내용 추가

---

src/apps/server/experiences/dto/res/updateExperienceInfo.dto.ts
src/apps/server/experiences/services/experience.service.ts

---
ai 자기소개서가 null로 들어오는 것을 잘못 체크하고 있어서 500에러가 발생해 수정합니다.
---
---
https://insightout.atlassian.net/browse/IO-30?atlOrigin=eyJpIjoiNTZiYzU3MmI3ZDE0NDA3Y2I5YTA2NjRiODE2YzBhMGMiLCJwIjoiaiJ9
---
---

[IO-30] fix: ai 자기소개서 null 체크 수정

---

src/apps/server/users/user.controller.ts
src/apps/server/users/user.module.ts
src/libs/modules/slack/slack.service.ts

---
피드백이 전송되면 DB에 쌓이긴 하는데, 별도의 알림이 없어서 슬랙에 알림이 오도록 기능을 추가했습니다.
---
---
https://insightout.atlassian.net/browse/IO-18?atlOrigin=eyJpIjoiZmIxYjBjM2NkNzgzNDk4ZDgwMzc3MWJkNDNiNmJiODIiLCJwIjoiaiJ9
---
---

[IO-18] 피드백 전송 시 슬랙에도 메시지 전송

---

.github/workflows/deploy-main.yml
scripts/deploy-before.sh

---
배포 과정에서 에러가 발생합니다.
github actions로 zip 파일로 s3에 저장 및 배포를 하게 되는데 이 과정에서 Symlink 가 아니라 일반 디렉터리로 지정되어서 에러가 발생하는 것으로 보입니다.
https://github.com/prisma/prisma/issues/15881#issuecomment-1287170234
```
AH. I may have found something:
locally, the content of node_modules/.bin are symlinks
lrwxr-xr-x    24 USER 21 oct 09:48  prisma -> ../prisma/build/index.js
lrwxr-xr-x    24 USER 21 oct 09:48  prisma2 -> ../prisma/build/index.js
on Azure, it seems they're not symlinks (!!!)
4140 -rwxrwxrwx 1 nobody nogroup 4235759 Oct 21 09:48 prisma
4140 -rwxrwxrwx 1 nobody nogroup 4235759 Oct 21 09:48 prisma2
Could it be the cause (I have a strong hint here...) ?
I'll dig further (on monday), with following refs:
https://github.com/projectkudu/kudu/issues/2946.
https://github.com/Azure/webapps-deploy/issues/54 …
```

ci: 배포 스크립트 수정

---

.github/workflows/deploy-main.yml
package.json
src/apps/server/main.ts
src/libs/modules/env/env.enum.ts
yarn.lock

feat: swagger 암호화
