depromeet/InsightOut-Server

- src/apps/server/app.module.ts
- src/apps/server/auth/auth.module.ts
- src/apps/server/resumes/resumes.controller.ts
- src/apps/server/resumes/resumes.module.ts
- src/apps/server/resumes/resumes.service.ts
- src/apps/server/test/test.controller.ts
- src/apps/server/test/test.module.ts
- src/apps/server/test/test.service.ts
- src/libs/utils/respone.entity.ts
- src/modules/database/repositories/abstract.repository.ts
- src/modules/database/repositories/resume.repository.ts
#37 에서의 기능을 추가했습니다.
- 추가로 findMany 등의 메서드를 작성하지 않아도, 추상 레포지터리를 구현하면 별도 메서드 추가 없이 사용 가능
- 응답을 일관되게 전달하기 위해서 응답 엔티티를 추가했습니다.
- 에러 메시지에 대한 응답 엔티티는 별도 추가가 필요해보입니다.(현재 구현된 소스코드로는 에러 발생 시의 응답과, 2xx 상태의 응답의 형태가 다릅니다)
물론 사용하지 않아도 좋습니다!
POST /test/token
```ts
// request body
{
"userId": number
}
````
테스트 토큰 발급 api의 바디에 userId를 넣어서 액세스 토큰을 발급받습니다. 테스트하기 용이하게 하려고 만들었어요.
레포지터리 테스트하려고 만들었는데 그냥 써도 괜찮을 것 같아요..? 아니면 쿼리를 조금 수정해야 할 수도..?
> [Feature] 추상 레포지터리 설정 및 응답 엔티티 추가, 테스트용 액세스 토큰 발급 api 추가, 자기소개서 조회 api 추가

- src/apps/server/auth/auth.service.ts
- src/apps/server/test/test.controller.ts
- src/apps/server/test/test.module.ts
- src/apps/server/test/test.service.ts
- 실수로 환경변수를 잘못 기입해서 수정했습니다.
- 리프레시 토큰의 만료 기한이 액세스 토큰과 같은 값을 가지고 있었고, 단위가 ms가 아니라 s라서 1000 곱한 것을 제거했습니다.
> [Fix] token 발급 방식에서의 오류 수정, 테스트 refresh 토큰 발급 추가

- src/apps/server/main.ts
- src/libs/modules/database/schema.prisma
- src/libs/utils/date.ts
- tsconfig.json
---
https://www.notion.so/depromeet/05-27-x-or-7438bc04b7034ce8aced336a5d92d9d9#8bc6ba6376154b7ca94b20724a0c0839
위 노션 페이지 내용대로, 각 컬럼별 필요한 속성들을 업데이트 했습니다.
---
1. 경험분해의 경우 제목이 25글자, 각 본문들이 대개 100글자이며, AI 역량 분석은 화면상 최대 167자이므로 160자를 제한으로 뒀습니다.
2. 경험분해의 startDate와 endDate를 Date 타입으로 바꿨습니다. string으로 되어있어서 정렬에 어려움이 있었습니다.
3. 역량 테이블을 생성했습니다. -> 경험과 역량이 N:M이므로 중간에 junction 테이블을 하나 두었습니다.
---
#65 
---
일단 startDate와 endDate를 DB에 저장할 때, new Date로 인스턴스화하고 담는데, 혹시 UTC로 변환되면서 날짜가 바뀌지 않을까 걱정이 됩니다.
---
동현님 PR 템플릿 덕분에 PR 작성이 넘나리 쉽자나~~~~~~~~~~난 너무 행복해 복 받았어
> [Feature] 컬럼 속성 업데이트

- src/apps/server/main.ts
---
ec2에서 build 할 때 무중단 서버 실행을 위해서 pm2로 서버를 구동하는데, 이게 명령어를 달리 해서 swagger가 뜨지 않습니다. 그래서 스웨거를 별도로 분기처리 하지 않고 공통으로 쓸 수 있도록 하고자 합니다.
---
```ts
//Swagger
switch (NODE_ENV) {
case NodeEnvEnum.Dev:
(() => {
const config = new DocumentBuilder()
.setTitle('13기 4팀 서버')
.setDescription('자기소개서 관리 시스템 🚨🚨🚨🚨 모든 성공 response 값은 메세지 또는 data 프로퍼티 안에 있습니다.🚨🚨🚨')
.addServer(`http://localhost:${envService.get(EnvEnum.PORT)}`, '로컬서버')
.addServer(`${envService.get(EnvEnum.DEV_SERVER)}:${envService.get(EnvEnum.PORT)}`, '개발서버')
.addServer(`${envService.get(EnvEnum.STAGE_SERVER)}:${envService.get(EnvEnum.PORT)}`, '스테이트서버')
.addServer(`${envService.get(EnvEnum.MAIN_SERVER)}:${envService.get(EnvEnum.PORT)}`, '운영서버')
.addBearerAuth()
.build();
const document = SwaggerModule.createDocument(app, config); …
```
> [Feature] Swagger 설정을 공통으로 적용

- src/apps/server/main.ts
- src/apps/server/resumes/controllers/question.controller.ts
- src/apps/server/resumes/controllers/resumes.controller.ts
- src/apps/server/resumes/dtos/get-resume.dto.ts
- src/apps/server/resumes/dtos/post-question.dto.ts
- src/apps/server/resumes/dtos/post-resume.dto.ts
- src/apps/server/resumes/services/question.service.ts
- src/apps/server/resumes/services/resumes.service.ts
- src/libs/modules/database/schema.prisma
---
해당 화면에서 자기소개서 단일 조회가 필요하므로 단일 조회 API를 하나 생성했습니다.
자기소개서 관련 API가 리팩터링이 필요했습니다. RESTful하게 작성하지 않은 부분을 수정했습니다.
자기소개서 조회 관련 명세를 추가했습니다. 화면도 함께 첨부하면서 프론트엔드에서 더 편하게 사용할 수 있도록 했습니다.
---
```ts
/**
* 한 개의 자기소개서를 조회합니다.
*
* userId와 resumeId로 특정 자기소개서를 한 개 가져오며, 자기소개서에 해당하는 문항들도 가져옵니다.
* 기본적으로 화면 단에서 생성일자 기준 내림차순(최신순)으로 정렬됩니다.
*
* @param userId 유저 id
* @param resumeId 자기소개서 id
* @returns 자기소개서와 자기소개서 문항을 가져옵니다.
*/
public async getOneResume(userId: number, resumeId: number): Promise<GetOneResumeResponseDto> {
const resume = await this.resumesRepository.findFirst({
where: { userId, id: resumeId },
include: { Question: { select: { title: true, answer: true, updatedAt: true }, orderBy: { createdAt: 'desc' } } }, // 자기소개서 문항을 left join, select 하며, 생성일자 기준 내림차순으로 모두 가져옵니다.
});
// Entity -> DTO
const …
```
> [Feature] 자기소개서 단일 조회 API 추가 및 자기소개서 API 관련 리팩터링, 자기소개서 조회 관련 명세 추가

- src/apps/server/common/decorators/validation/isTrue.decorator.ts
- src/apps/server/onboarding/docs/patch-onboarding.doc.ts
- src/apps/server/onboarding/dtos/patch-onboarding.dto.ts
- src/apps/server/onboarding/onboarding.controller.ts
- src/apps/server/onboarding/onboarding.service.ts
- src/apps/server/resumes/controllers/resumes.controller.ts
- src/apps/server/resumes/dtos/get-resume.dto.ts
- src/apps/server/resumes/services/resumes.service.ts
- src/libs/modules/database/schema.prisma
---
온보딩 여부를 업데이트 하는 API 가 필요합니다. 온보딩이 모두 종료되고 업데이트 해야 다음 번애 동일한 온보딩/툴팁을 뱉지 않기 때문입니다.
---
```ts
async updateOnboarding(userId: number, onboardings: Omit<Partial<Onboarding>, 'userId'>): Promise<PatchOnboardingResponseDto> {
if (!Object.keys(onboardings).length) {
throw new BadRequestException('Please include onboarding at least 1.');
}
const updatedOnboarding = await this.onboardingRepository.update({
where: { userId },
data: onboardings,
});
const updateOnboardingResponseDto = new PatchOnboardingResponseDto(updatedOnboarding);
return updateOnboardingResponseDto;
}
```
값이 하나라도 없으면 예외를 일으킵니다. 온보딩 된 것을 파악하여 업데이트합니다.
---
#112 
---
request body에서 experience를 false로 둬도 업데이트가 발생하는 게 너무 아쉽습니다.
그래서 `@ValidateIf()` 데코레이터를 사용하려고 하는데요,
```ts
@ValidateIf((o) => o.experience)
get experience(): boolean …
```
> [Feature] 온보딩 업데이트 API 추가

- src/apps/server/app.module.ts
- src/apps/server/collections/collection.controller.ts
- src/apps/server/collections/collection.module.ts
- src/apps/server/collections/collection.service.ts
- src/apps/server/collections/docs/get-count-of-experience-and-resume.doc.ts
- src/apps/server/collections/dtos/get-count-of-experience-and-resume.dto.ts
- src/libs/modules/database/repositories/experience.repository.ts
---
모아보기 상단에 있는 경험 카드 개수와 자기소개서의 개수를 확인합니다.
---
경험 카드와 자기소개서 개수를 가져와서 반환합니다.
```ts
async getCountOfExperienceAndResume(userId: number): Promise<GetCountOfExperienceAndResumeResponseDto> {
const countOfExperience = await this.experienceRepository.countExperience(userId);
const countOfResume = await this.resumeRepository.count({
where: { userId },
});
const getCountOfExperienceAndResumeResponseDto = new GetCountOfExperienceAndResumeResponseDto(countOfExperience, countOfResume);
return getCountOfExperienceAndResumeResponseDto;
}
```
두 번의 count 쿼리가 생기고 response dto를 만들어 반환합니다.
---
#121 
---
현재 모아보기에서 필요할 API는
1. 경험카드 자기소개서 count API
2. 경험카드 역량 키워드 조회 및 count API
3. 자기소개서 제목 조회API
4. 경험 카드 역량 키워드 별(혹은 전체 카드) 전체 조회 API,
5. 특정 자기소개서 1개 조회 API
일단 이 정도로 보이는데 모아보기쪽에서 API가 추가되거나 삭제할 만한 내용이 있을까요?
---
> [Feature] 경험 카드와 자기소개서 count API

- src/apps/server/resumes/controllers/question.controller.ts
- src/apps/server/resumes/controllers/resumes.controller.ts
- src/apps/server/resumes/docs/post-spell-check.doc.ts
- src/apps/server/resumes/dtos/get-resume.dto.ts
- src/apps/server/resumes/dtos/patch-question-request.dto.ts
- src/apps/server/resumes/dtos/patch-resume.dto.ts
- src/apps/server/resumes/dtos/post-spell-check-request.body.dto.ts
- src/apps/server/resumes/services/question.service.ts
- src/apps/server/resumes/services/resumes.service.ts
- src/libs/modules/api/api.service.ts
- src/libs/modules/database/schema.prisma
- src/libs/utils/hanspell.function.ts
---
- 문항 조회에 createdAt 추가
- 특정 자기소개서 조회 실패 시 예외 처리 추가
- 문항 별 maxLength 수정
- 맞춤법 검사 API 경로 수정
---
```ts
public async getOneResume(userId: number, resumeId: number): Promise<GetOneResumeResponseDto> {
const resume = await this.resumesRepository.findFirst({
where: { userId, id: resumeId },
include: {
Question: { select: { id: true, title: true, answer: true, createdAt: true, updatedAt: true }, orderBy: { createdAt: 'desc' } },
}, // 자기소개서 문항을 left join, select 하며, 생성일자 기준 내림차순으로 모두 가져옵니다.
});
if (!resume) {
throw new NotFoundException('Resume not found');
}
// Entity -> DTO
const getOneResumeDto = new GetOneResumeResponseDto(resume as Resume & { Question: Question[] });
return getOneResumeDto;
}
```
자기소개서가 없으면 예외를 일으킵니다.
---
#130 
---
---
> [Fix, Refactor] 자기소개서 부분 API 수정

- src/apps/server/experiences/dto/res/getExperience.res.dto.ts
- src/apps/server/resumes/controllers/question.controller.ts
- src/apps/server/resumes/docs/patch-question.doc.ts
- src/apps/server/resumes/dtos/patch-question-request.dto.ts
- src/apps/server/resumes/services/question.service.ts
- src/apps/server/users/docs/patch-user-info.doc.ts
- src/apps/server/users/dtos/patch-user-info.dto.ts
- src/apps/server/users/user.controller.ts
- src/apps/server/users/user.service.ts
- src/libs/modules/database/schema.prisma
---
마이페이지에서 유저 정보가 수정 가능하므로, 해당 기능을 구현했습니다.
---
```ts
async updateUserInfo(userId: number, body: PatchUserInfoRequestBodyDto): Promise<void> {
if (!Object.keys(body).length) {
throw new BadRequestException('Please input information to be updated');
}
await this.userRepository.update({
data: { nickname: body.nickname, UserInfo: { update: { field: body.field } } },
where: { id: userId },
});
}
```
유저 정보 중 image는 현 MVP가 아니고, 구글 계정은 유저가 임의로 바꿀 수 없으므로,
nickname과 field(직무 분야)만 바꿀 수 있습니다.
---
#132 
---
---
> [Feature] 유저 정보 수정 API

- src/apps/server/common/consts/experience-attribute.const.ts
- src/apps/server/experiences/controllers/experience.controller.ts
- src/apps/server/experiences/dto/req/get-experience.dto.ts
- src/apps/server/experiences/dto/res/getExperience.res.dto.ts
- src/apps/server/experiences/markdown/experience.md.ts
- src/apps/server/experiences/services/experience.service.ts
- src/apps/server/resumes/controllers/resumes.controller.ts
- src/libs/modules/database/repositories/experience.repository.ts
---
경험카드를 조회할 때 s, t, a, r에 대한 쿼리를 추가하여 각각을 개별적으로 가져옵니다.
GET /experience 를 사용하는 페이지가 많기 때문에 한 번 통제하고 RESTful 하게 API를 구현하고자 합니다.
---
situation, task, action, result 각각에 쿼리 요청을 보내서 원하는 값만 응답에 넣을 수 있도록 합니다.
모아보기에서는 situation을 사용하며, 경험 분해 페이지에서는 situation, task, action, result를 모두 사용하고, 자기소개서 페이지에서 경험 카드를 조회할 때는 사용하지 않습니다.
---
#143 
---
---
> [Feature] 경험분해 API에서 query string 추가하여 s, t, a, r 조회 

- src/libs/modules/database/schema.prisma
---
첫 가입 및 마이페이지에서의 유저 직무에서 비즈니스와 토목에 대한 선택권을 삭제합니다.
---
스키마에서 비즈니스와 토목을 없앴습니다.
---
#148 
---
---
> feat: 유저 직무에서 비즈니스와 토목 삭제

- src/apps/server/resumes/services/resume.service.spec.ts
---
get resumes 에서 값을 못 찾았을 때의 경우를 테스트합니다.
정확히는 `getAllResumes` 메서드에 대해서 테스트했습니다.
---
---
#166 
---
테스트 코드를 거의 안 짜봐서 이게 맞나... 싶군요
---
> [Test] get resumes에서 아무 값도 없을 때 테스트

- src/apps/server/ai/ai.controller.ts
- src/apps/server/ai/ai.service.ts
- src/apps/server/ai/dto/req/promptSummary.req.dto.ts
- src/apps/server/ai/dto/res/promptSummary.res.dto.ts
- src/apps/server/ai/markdown/ai.md.ts
- src/apps/server/ai/prompt/keywordPrompt.ts
- src/libs/modules/env/env.enum.ts
- 경험 카드 STAR를 요약하는 API를 구현했습니다.
---
---
#171 
---
1.  경험 요약 같은 경우에는 Chat GPT의 요약본을 받고 바로 analysis에 저장하는 것 까지 포함 해야 될 거 같은데 어떻게 생각하시나요?!
- 아래 사진 처럼 Chat GPT요청 이후에 바로 카드를 보여주기 때문에 이 시점에 저장을 해야 될 거 같아요!
2. 다른 방법은 요약된 내용을 받고 다시 upsert API로 업데이트를 하는 것입니다!
- 인사이트를 하사하여 주세요 🙏 
---
---
> [#171] 경험 프로프트 요약 API 생성

- src/apps/server/common/exceptions/unknown.exception.ts
- src/apps/server/common/guards/jwt-auth.guard.ts
- src/apps/server/common/guards/jwt-refresh.guard.ts
---
TypeError가 발생하여 액세스 토큰 재발급 시 에러가 뜨는 부분을 수정합니다.
---
```ts
if (info?.message === 'No auth token') {
throw new NoAuthTokenException();
}
```
옵셔널 프로퍼티로 바꾸고 바로 해결했습니다.
---
#202 
---
---
> [Hotfix] guard property 접근 시 발생하는 에러 수정

- src/apps/server/experiences/controllers/experience.controller.ts
- src/apps/server/experiences/services/experience.service.ts
- src/libs/modules/database/repositories/experience.repository.ts
---
경험카드 조회할 때 userId를 where로 안 돌려서 모든 유저의 경험카드를 조회해버렸습니다.
---
경험카드 조회 시 userId를 검사해서 해당 유저의 경험카드만 가져오도록 수정했습니다.
```ts
public async getExperienceByCapability(userId: number, capabilityId: number, select: Partial<ExperienceSelect>) {
// TODO ai 역량 키워드가 적용되면 해당 키워드도 함께 쿼리로 가져와야 함.
const experiences = await this.prisma.experience.findMany({
where: { userId, ExperienceCapability: { some: { capabilityId: { equals: capabilityId } } } },
select: {
id: true,
title: true,
```
---
#201 
---
---
> [Fix] 경험카드 조회 시 모든 유저의 경험카드 가져오는 버그 수정

- src/libs/modules/database/repositories/experience.repository.ts
---
userId 없이 경험 카드를 조회해서 논리적인 오류가 발생하고 있었습니다.
---
userId를 where 안에 넣어주었습니다.
---
#226 
---
---
> [Hotfix] 모든 경험 카드 조회에서 유저 아이디 where절 누락 수정

- src/apps/server/onboarding/dtos/get-onboarding.dto.ts
- src/apps/server/onboarding/dtos/patch-onboarding.dto.ts
- src/libs/modules/database/schema.prisma
---
직무 온보딩 선택 여부가 필요해서 추가합니다.
회원가입 하는 유저와 로그인 하는 유저를 구분하는 데 필요하다고 하십니다.
---
```ts
// 회원가입 시 모든 온보딩 처리를 생성합니다.
model Onboarding {
userId Int @id
field             Boolean @default(false) // 직무 선택 온보딩
experience        Boolean @default(false) // 경험분해 온보딩 여부
experienceStepper Boolean @default(false) @map("experience_stepper") // 경험분해 stepper 온보딩 여부
resume            Boolean @default(false) // 자기소개서 작성 온보딩 여부
collection        Boolean @default(false) // 모아보기 온보딩 여부
User User @relation(references: [id], fields: [userId])
@@map("onboarding")
}
```
업데이트 된 온보딩 여부 테이블입니다.
---
#230 
---
---
> [Feature] 직무 선택 온보딩 경험 여부 컬럼 추가 & 회원가입/로그인 시 반환되는 온보딩 값에 직무 선택 온보딩 경험 여부 추가

- src/apps/server/experiences/dto/res/getExperienceById.res.dto.ts
- src/libs/modules/database/repositories/experience.repository.ts
- 경험 분해 단일 조회시 updatedAt을 내려달라는 요청 사항을 반영하였습니다.
---
- updatedAt이 함께 내려갑니다!
---
---
---
- @stae1102 저희 utilization 사라진 걸로 알고 있는데 제가 맞다면 이슈 만들어서 모두 삭제할 수 있도록 하겠습니다!
- 컨펌 부탁드립니다 :)
---
> [#248] 경험 분해 단일 조회시 updatedAt 내려주기

- src/apps/server/ai/ai.service.ts
---
ai 키워드 추천이 종종 2개까지 돼서 이 부분 수정합니다.
---
모든 ai 추천에 slice(0, 2) 프로토타입 메서드로 2개 이하로 추출합니다.
---
#273 
---
---
> [Feature] ai 키워드 종류의 추천을 2개까지만 추천하도록 개선

- src/apps/server/ai/ai.service.ts
- src/apps/server/experiences/dto/res/getExperienceById.res.dto.ts
- src/libs/modules/database/repositories/experience.repository.ts
- src/libs/modules/open-ai/open-ai.service.ts
---
앞으로 카드 뒷면을 포함한 카드 데이터를 모두 보여주므로, experienceId를 통한 단일 조회에 뒷면 데이터에 쓰이는 직무 역량 키워드 속성 추가
---
```ts
public async getExperienceById(experienceId: number): Promise<Partial<Experience & { ExperienceInfo; AiResume }>> {
return await this.prisma.experience.findUnique({
where: { id: experienceId },
select: {
id: true,
title: true,
startDate: true,
endDate: true,
situation: true,
task: true,
action: true,
result: true,
experienceStatus: true,
summaryKeywords: true,
updatedAt: true,
ExperienceInfo: { select: { experienceId: true, experienceRole: true, motivation: true } },
ExperienceCapability: { select: { Capability: { select: { id: true, keyword: true, keywordType: true } } } }, // 직무 역량 키워드 가져오기 추가
AiResume: {
select: { content: true, AiResumeCapability: { select: { Capability: { select: { …
```
> [Feature] 카드 뒷면 데이터에 필요한 유저 직무 역량 키워드 프로퍼티 추가

- src/libs/modules/database/schema.prisma
- Experience 삭제 시 등장하는 에러를 해결했습니다.
---
- experience와 capability를 1:N으로 연결했습니다.
- experience 삭제 시 capability의 experienceId가 null로 변경 되도록 cascade: SetNull구현했습니다.
- experience 삭제 시 aiResume의 experienceId가 null로 변경 되도록 cascade: SetNull구현했습니다.
---
#307 
---
---
---
> [#307] db 수정 및 SetNull변경

- src/apps/server/experiences/dto/res/getExperienceById.res.dto.ts
- src/libs/modules/database/repositories/experience.repository.ts
---
경험카드 다중 조회에서는 ai 자기소개서 추천 문항이 있지만, ai 단일 조회에는 없어서 추가했습니다.
---
---
#311 
---
---
> [Fix] 경험카드 단일 조회에서 AI 자기소개서 추천 문항을 반환하도록 수정

- src/apps/server/experiences/services/experience.service.ts
- src/libs/modules/database/repositories/capability.repository.ts
- src/libs/modules/database/repositories/experience.repository.ts
---
situation, task, action, result에 상관 없이 모두 있는지 체크하느라 에러가 발생해서, 쿼리로 들어온 애들만 조건문을 통해 걸러냈습니다.
---
- 경험카드 필터링 수정
```ts
experiences = experiences.filter((experience) => {
if (experience.experienceStatus === ExperienceStatus.DONE) {
let isValidExperience =
experience.title &&
experience.startDate instanceof Date &&
experience.endDate instanceof Date &&
experience.ExperienceCapabilities.length &&
true;
if (select.situation) {
isValidExperience = experience.situation && isValidExperience;
}
if (select.task) {
isValidExperience = experience.task && isValidExperience;
}
if (select.action) {
isValidExperience = experience.action && isValidExperience;
}
if (select.result) {
isValidExperience = experience.result && isValidExperience;
}
return isValidExperience;
}
return true;
});
```
- 경험 카드 개수 …
> [Fix] 경험 카드 키워드 로직 수정

- src/apps/server/experiences/services/experience.service.ts
- src/libs/modules/database/repositories/experience.repository.ts
---
경험분해 페이지네이션에서 총 itemCount로 NextPage와 PreviousPage를 찾는데, itemCount 자체에서 유효성 검사로 로직이 불가능해져서 새로 고쳤습니다.
---
```ts
public async getCount(userId: number, select: Partial<ExperienceSelect>, capabilityId?: number) {
const experiences = await this.getExperiences(userId, select, { skip: undefined, take: undefined }, capabilityId);
return experiences.length;
}
```
---
#314 
---
count로 가져오는 건 캐싱해서 써도 괜찮을 것 같다가도 저장하는 데이터가 많으니까 불안불안쓰 하군요..
나중에 ElasticCache 써서 redis 관리는 AWS에 위임시키는 것도 좋을 듯 합니다~
---
> [Fix] 경험분해 페이지네이션 개수 조회 수정
